In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('world_population.csv')
#Sorting and Indexing by range of ranks
upper_limit=20 #The upper limit of the range of ranks (the smaller number)
lower_limit=25 #The lower limit of the range of ranks (the bigger number)
dfranks = df[(df["Rank"] <= lower_limit) & (df["Rank"] >= upper_limit)].sort_values(by="Rank", ascending=True).set_index("Rank")
dfranks

,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Rank,,,,,,,,,,,,,,,,
20,THA,Thailand,Bangkok,Asia,71697030.0,71475664.0,70294397.0,68270489.0,63066603.0,55228410.0,45737753.0,NaN,513120.0,139.7276,1.0013,0.90
21,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
22,TZA,Tanzania,Dodoma,Africa,65497748.0,61704518.0,52542823.0,45110527.0,34463704.0,26206012.0,19297659.0,13618192.0,945087.0,69.3034,1.0300,0.82
23,FRA,France,Paris,Europe,64626628.0,64480053.0,63809769.0,62444567.0,58665453.0,56412897.0,53713830.0,50523586.0,551695.0,117.1419,1.0015,0.81
24,ZAF,South Africa,Pretoria,Africa,59893885.0,58801927.0,55876504.0,51784921.0,46813266.0,39877570.0,29463549.0,22368306.0,1221037.0,49.0517,1.0084,0.75
25,ITA,Italy,Rome,Europe,59037474.0,59500579.0,60232906.0,59822450.0,56966397.0,56756561.0,56329482.0,53324036.0,301336.0,195.9191,0.9966,0.74

In [5]:
#Sorting and indexing by continent
continents="Asia Africa" #The list of continents in which the countries  are located, seperated by spaces
continents=continents.split()
dfcontinents = df[df["Continent"].isin(continents)].sort_values(by="Continent").set_index("Continent")
dfcontinents

,Rank,CCA3,Country,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,,,,,
Africa,62,MWI,Malawi,Lilongwe,20405317.0,19377061.0,16938942.0,14718422.0,11229387.0,9539665.0,6267369.0,4625141.0,118484.0,172.2200,1.0259,0.26
Africa,147,LSO,Lesotho,Maseru,2305825.0,2254100.0,2118521.0,2022747.0,1998630.0,1798997.0,1407672.0,1023481.0,30355.0,75.9620,1.0107,0.03
Africa,121,LBR,Liberia,Monrovia,5302681.0,5087584.0,4612329.0,4019956.0,2895224.0,2209731.0,1932169.0,1463563.0,111369.0,47.6136,1.0210,0.07
Africa,107,LBY,Libya,Tripoli,6812341.0,6653942.0,6192235.0,6491988.0,5154790.0,4236983.0,2962720.0,1909177.0,1759540.0,3.8717,1.0114,0.09
Africa,50,MDG,Madagascar,Antananarivo,29611714.0,28225177.0,24850912.0,21731053.0,16216431.0,11882762.0,8948162.0,6639751.0,587041.0,50.4423,1.0241,0.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Asia,122,PSE,Palestine,Ramallah,5250072.0,5019401.0,4484614.0,3992278.0,3139954.0,2124609.0,1453620.0,1118241.0,6220.0,844.0630,1.0227,0.07
Asia,13,PHL,Philippines,Manila,115559009.0,112190977.0,103031365.0,94636700.0,77958223.0,61558898.0,48419546.0,37435586.0,342353.0,337.5434,1.0147,1.45
Asia,143,QAT,Qatar,Doha,2695122.0,2760385.0,2414573.0,1713504.0,645937.0,441675.0,277450.0,118007.0,11586.0,232.6189,1.0026,0.03
Asia,41,SAU,Saudi Arabia,Riyadh,36408820.0,35997107.0,32749848.0,29411929.0,21547390.0,16004763.0,10171710.0,6106191.0,2149690.0,16.9368,1.0128,0.46
Asia,36,AFG,Afghanistan,Kabul,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52

In [6]:
countries_list="Canada Bulgaria Fiji Finland Guam Laos Malta Mali" #Enter the list of countries you would like to see, seperated by spaces
countries_list=countries_list.split()
dfcountries = df[df["Country"].isin(countries_list)].sort_values(by="Country").set_index("Country")
dfcountries

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Bulgaria,108,BGR,Sofia,Europe,6781953.0,6979175.0,7309253.0,7592273.0,8097691.0,8767778.0,8980606.0,8582950.0,110879.0,61.1654,0.9849,0.09
Canada,39,CAN,Ottawa,North America,38454327.0,37888705.0,35732126.0,33963412.0,30683313.0,27657204.0,24511510.0,21434577.0,9984670.0,3.8513,1.0078,0.48
Fiji,162,FJI,Suva,Oceania,929766.0,920422.0,917200.0,905169.0,832509.0,780430.0,644582.0,527634.0,18272.0,50.8847,1.0056,0.01
Finland,118,FIN,Helsinki,Europe,5540745.0,5529468.0,5479461.0,5363271.0,5176209.0,4986545.0,4779418.0,4606621.0,338424.0,16.3722,1.0009,0.07
Guam,191,GUM,Hagåtña,Oceania,171774.0,169231.0,167978.0,164905.0,160188.0,138263.0,110286.0,88300.0,549.0,312.8852,1.0073,0.00
Laos,103,LAO,Vientiane,Asia,7529475.0,7319399.0,6787419.0,6323418.0,5430853.0,4314443.0,3297519.0,2675283.0,236800.0,31.7968,1.0141,0.09
Mali,59,MLI,Bamako,Africa,22593590.0,21224040.0,18112907.0,15529181.0,11239101.0,8945026.0,7372581.0,6153587.0,1240192.0,18.2178,1.0314,0.28
Malta,173,MLT,Valletta,Europe,533286.0,515357.0,456579.0,418755.0,399212.0,365392.0,333587.0,315414.0,316.0,1687.6139,1.0124,0.01