In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('Flavors.csv')
grouped_flavors=df.groupby("Base Flavor")[["Flavor Rating", "Texture Rating", "Total Rating"]].agg(["count", "sum", "mean", "max"])
grouped_flavors

            Flavor Rating                  Texture Rating                  \
                    count   sum mean   max          count   sum      mean
Base Flavor
Chocolate               3  25.2  8.4   8.8              3  21.7  7.233333
Vanilla                 6  34.2  5.7  10.0              6  33.9  5.650000

                 Total Rating
             max        count   sum   mean   max
Base Flavor
Chocolate    7.6            3  47.1  15.70  16.6
Vanilla      8.0            6  68.1  11.35  18.0

In [10]:
df.groupby("Base Flavor").describe()

            Flavor Rating                                             \
                    count mean       std  min    25%  50%  75%   max
Base Flavor
Chocolate             3.0  8.4  0.346410  8.2  8.200  8.2  8.5   8.8
Vanilla               6.0  5.7  2.710719  2.3  4.025  5.6  6.8  10.0

            Texture Rating            ...             Total Rating         \
                     count      mean  ...    75%  max        count   mean
Base Flavor                           ...
Chocolate              3.0  7.233333  ...  7.350  7.6          3.0  15.70
Vanilla                6.0  5.650000  ...  6.375  8.0          6.0  11.35


                  std   min     25%   50%     75%   max
Base Flavor
Chocolate    0.781025  15.2  15.250  15.3  15.950  16.6
Vanilla      4.263684   5.7   9.025  11.1  13.175  18.0

[2 rows x 24 columns]